New changes
annapirova/mp2-lab2-matrix pull request #4
Opened 2021-10-17 11:43 UTC by artemchikk

Здравствуйте! Вроде бы, все работает.

2021-10-17 14:42 UTC, annapirova requested changes
Артем, 
1. Половина функций вектора не учитывает StartIndex, а должна. (==, +, -)
2. В матрице все перегрузки, для которых можно вызвать перегрузку из вектора, должны это делать. Можно сократить код раза в полтора
3. Мне кажется, конструктор матриц неправильный. Там строки д.б. уменьшающейся длины, а не одинаковой.
4. Часть тестов вектора бесполезные, т.к. вектора пустые. Просмотрите все тесты, добавьте значения.
5. EXPECT_EQ(правильный ответ, проверяемое значение). У вас наоборот

2021-10-17 17:38 UTC, artemchikk commented
У меня конструктор вектора немного другой из-за этого матрица должна получаться такой как надо. Если я все правильно понял, то те тесты что пустые проверяют кол-во элементов, там не важно какие значения они будут принимать. Не понял про какие EXPECT_EQ вы говорите, но вроде бы никакой разницы, тут проверяется равенство и оба числа должны быть одинаковыми, и если вдруг это не так, то тест сработает в любом случаи.

2021-10-19 07:31 UTC, annapirova commented
Артем, все равно половину замечаний не исправили. 
Остались функции без StartIndex, в TMаtrix функции могут вызывать перегрузку из TVector вместо своего кода

2021-11-07 19:09 UTC, artemchikk commented
Переделал вторую лабу. Третью постараюсь завтра отправить.

2021-11-10 06:04 UTC, annapirova commented
Лаба засчитана, но можно придираться.
А в чем смысл изменений, что вы переделали 
for (int i = 0; i < Size; i++) 
        temp.pVector[i] = temp.pVector[i] + v.pVector[i];
и подобные места?

2021-11-23 12:21 UTC, closed without merging